/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luciad_imageio_webp_WebPEncoderOptions */

#ifndef _Included_com_luciad_imageio_webp_WebPEncoderOptions
#define _Included_com_luciad_imageio_webp_WebPEncoderOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    createConfig
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_createConfig
  (JNIEnv *, jclass);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    deleteConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_deleteConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getLossless
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getLossless
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setLossless
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setLossless
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getQuality
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getQuality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setQuality
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setQuality
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setMethod
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setMethod
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getTargetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getTargetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setTargetSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setTargetSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getTargetPSNR
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getTargetPSNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setTargetPSNR
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setTargetPSNR
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getSegments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getSegments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setSegments
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setSegments
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getSnsStrength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getSnsStrength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setSnsStrength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setSnsStrength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getFilterStrength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getFilterStrength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setFilterStrength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setFilterStrength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getFilterSharpness
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getFilterSharpness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setFilterSharpness
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setFilterSharpness
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getFilterType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getFilterType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setFilterType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setFilterType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getAutofilter
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getAutofilter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setAutofilter
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setAutofilter
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getAlphaCompression
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getAlphaCompression
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setAlphaCompression
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setAlphaCompression
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getAlphaFiltering
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getAlphaFiltering
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setAlphaFiltering
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setAlphaFiltering
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getAlphaQuality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getAlphaQuality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setAlphaQuality
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setAlphaQuality
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getPass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getPass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setPass
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setPass
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getShowCompressed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getShowCompressed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setShowCompressed
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setShowCompressed
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getPreprocessing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getPreprocessing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setPreprocessing
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setPreprocessing
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getPartitions
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getPartitions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setPartitions
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setPartitions
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getPartitionLimit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getPartitionLimit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setPartitionLimit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setPartitionLimit
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getEmulateJpegSize
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getEmulateJpegSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setEmulateJpegSize
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setEmulateJpegSize
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getThreadLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getThreadLevel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setThreadLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setThreadLevel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getLowMemory
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getLowMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setLowMemory
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setLowMemory
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getNearLossless
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getNearLossless
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setNearLossless
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setNearLossless
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getExact
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getExact
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setExact
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setExact
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getUseDeltaPalette
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getUseDeltaPalette
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setUseDeltaPalette
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setUseDeltaPalette
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getUseSharpYUV
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getUseSharpYUV
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setUseSharpYUV
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setUseSharpYUV
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getQMin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getQMin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setQMin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setQMin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    getQMax
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_getQMax
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPEncoderOptions
 * Method:    setQMax
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPEncoderOptions_setQMax
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
