/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luciad_imageio_webp_WebPDecoderOptions */

#ifndef _Included_com_luciad_imageio_webp_WebPDecoderOptions
#define _Included_com_luciad_imageio_webp_WebPDecoderOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    createDecoderOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_createDecoderOptions
  (JNIEnv *, jclass);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    deleteDecoderOptions
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_deleteDecoderOptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getBypassFiltering
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getBypassFiltering
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setBypassFiltering
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setBypassFiltering
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getNoFancyUpsampling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getNoFancyUpsampling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setNoFancyUpsampling
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setNoFancyUpsampling
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getUseCropping
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getUseCropping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getCropLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getCropLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setCropLeft
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setCropLeft
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getCropTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getCropTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setCropTop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setCropTop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setUseCropping
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setUseCropping
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getCropWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getCropWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setCropWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setCropWidth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getCropHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getCropHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setCropHeight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setCropHeight
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getUseScaling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getUseScaling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getScaledWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getScaledWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setScaledWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setScaledWidth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setUseScaling
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setUseScaling
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getScaledHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getScaledHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setScaledHeight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setScaledHeight
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getUseThreads
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getUseThreads
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setUseThreads
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setUseThreads
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getDitheringStrength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getDitheringStrength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setDitheringStrength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setDitheringStrength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getFlip
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getFlip
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setFlip
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setFlip
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    getAlphaDitheringStrength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_getAlphaDitheringStrength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPDecoderOptions
 * Method:    setAlphaDitheringStrength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPDecoderOptions_setAlphaDitheringStrength
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
