name: Diffuse

on:
  pull_request:
    branches:
      - master
      - main
      - trunk
      - develop
      - maine
      - mane

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
  
permissions:
  contents: read
  pull-requests: write

jobs:
  run-diffuse:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
          printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version-file: .java-version

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew assemble

      - run: find . -regex ".*webp-imageio/build/libs/webp-imageio-[0-9SNAPSHOT\.-]*\.jar" -print | xargs -n 1 -I % cp % pull-request-artifact.jar
        shell: bash

      - name: Check size
        run: du -h pull-request-artifact.jar
        shell: bash

      - uses: actions/cache@v4
        name: Download base
        with:
          path: |
            diffuse-source-file
          key: diffuse-${{ github.event.pull_request.base.sha }}
          restore-keys: diffuse-${{ github.event.pull_request.base.sha }}

      - id: diffuse
        uses: usefulness/diffuse-action@v1
        with:
          old-file-path: diffuse-source-file
          new-file-path: pull-request-artifact.jar

      - uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Diffuse output

      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ steps.diffuse.outputs.diff-gh-comment != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            ### Jar size:
            Jar size change: ${{ steps.diffuse.outputs.size-diff-comment_style_1 }}
            ### Diffuse output:
            ${{ steps.diffuse.outputs.diff-gh-comment }}
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: diffuse-output
          path: ${{ steps.diffuse.outputs.diff-file }}
